name: autopost
on:
  schedule:
    - cron: "17 * * * *"   # hourly at :17 UTC
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install dependency
        run: pip install playwright==1.47.0
      - name: Install Playwright
        run: python -m playwright install --with-deps chromium
      - name: Run poster
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
          CONTACT_PHONE: ${{ secrets.CONTACT_PHONE }}
          BRAND_NAME: ${{ secrets.BRAND_NAME }}
        run: python poster.py
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: autoposter-artifacts
          path: data/
          if-no-files-found: ignore
