name: autopost
on:
  schedule:
    - cron: "17 13,18,23 * * *"   # 3x daily UTC
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - name: Install Playwright
        run: python -m playwright install --with-deps chromium
      - name: Run poster
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
          CONTACT_PHONE: ${{ secrets.CONTACT_PHONE }}
          BRAND_NAME: ${{ secrets.BRAND_NAME }}
        run: python poster.py
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: post-logs
          path: data/posts.csv
          if-no-files-found: ignore
